---
version: '3'

tasks:
  validate:
    cmds:
      - packer validate -var-file='packer/ubuntu/22-04-lts/variables.pkrvars.hcl' packer/ubuntu/22-04-lts/

  build:
    cmds:
      - packer build -warn-on-undeclared-var -var-file='packer/ubuntu/22-04-lts/variables.pkrvars.hcl' packer/ubuntu/22-04-lts/
